# Generated by Django 5.1.2 on 2025-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('collections', models.IntegerField()),
                ('r_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='gmail',
        ),
    ]
