# Generated by Django 5.1.2 on 2025-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0002_movies_review_rename_email_students_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_review',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
