# Generated by Django 5.1.2 on 2025-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0003_movies_review_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
