# Generated by Django 5.1.2 on 2025-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0004_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
