# Generated by Django 5.1.2 on 2025-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0005_alter_employees_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_review',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
