# Generated by Django 5.1.2 on 2025-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0006_alter_movies_review_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_users_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
