# Generated by Django 5.1.2 on 2025-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0007_basic_users_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_users_login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
